# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en"
title                    : "Causality Data Science"
name                     : "Matheus Rabetti"
description              : "Enlightened trial and error outperforms the planning of flawless execution"
url                      : "https://matheusrabetti.github.io"
baseurl                  : ""
repository               : "matheusrabetti/matheusrabetti.github.io"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"


# Site Author
author:
  name             : "Matheus Rabetti"
  avatar           : "/assets/avatar-icon.jpg"
  bio              : "Experimentation & Data Science @ Uber"
  disqus-shortname : matheusrabetti
  location         : "Brasília, Brazil"
  email            : "matheus.rabetti@gmail.com"
  uri              :
  facebook         :
  github           : MatheusRabetti
  linkedin         : matheus-r-8977b49b
  stackoverflow    : # "123456/username" (the last part of your profile url, e.g. http://stackoverflow.com/users/123456/username)
  twitter          :
  google:
    analytics      : "UA-83714078-1" 



# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
  
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-gist

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
enable_coderay: false

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author_profile: true
      read_time: false
      comments: true
      share: true

